# Generated by Django 3.2 on 2022-02-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wydawcy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wydawca', models.CharField(max_length=30)),
                ('tytuł', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=50)),
                ('ISBN', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'książka',
                'verbose_name_plural': 'książki',
            },
        ),
        migrations.AlterModelOptions(
            name='ksiazki',
            options={'verbose_name': 'książka', 'verbose_name_plural': 'książki'},
        ),
    ]
