# Generated by Django 3.2 on 2022-02-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0002_auto_20220205_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wydawcy',
            options={'verbose_name': 'wydawca', 'verbose_name_plural': 'wydawcy'},
        ),
        migrations.AddField(
            model_name='ksiazki',
            name='wydawca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ksiazki.wydawcy'),
        ),
    ]
