# Generated by Django 3.2 on 2022-02-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0003_auto_20220205_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksiazki',
            name='wydawca',
        ),
    ]
