# Generated by Django 3.2 on 2022-02-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0004_remove_ksiazki_wydawca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazki',
            name='link',
            field=models.URLField(),
        ),
    ]
