# Generated by Django 3.2 on 2022-02-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0005_alter_ksiazki_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wydawcy',
        ),
    ]
