# Generated by Django 3.2 on 2022-02-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0006_delete_wydawcy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazki',
            name='ISBN',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='jezyk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='strony',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='tytuł',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
